import {
  bgColorClass,
  borderColorClass,
  borderWidthClass,
  fontSizeClass,
  hoverClass,
  paddingClass,
  paddingXClass,
  paddingYClass,
  shadowClass,
  textColorClass,
} from '../../theme';

function flattenClassList(...args: (string | string[])[]): string {
  return args.flat().filter(Boolean).join(' ');
}

export const buttonVariantClass = {
  solid: flattenClassList(
    fontSizeClass.buttonText,
    paddingClass.md,
    bgColorClass.black,
    textColorClass.white,
    hoverClass.opacity,
    shadowClass.md,
  ),
  soft: flattenClassList(
    fontSizeClass.buttonText,
    paddingClass.md,
    bgColorClass.white,
    textColorClass.black,
    borderWidthClass.base,
    borderColorClass.black,
    hoverClass.opacity,
    shadowClass.sm,
  ),
  thin: flattenClassList(
    fontSizeClass.xs,
    paddingClass.xs,
    bgColorClass.black,
    textColorClass.white,
    hoverClass.opacity,
    shadowClass.sm,
  ),
  outline: flattenClassList(
    fontSizeClass.buttonText,
    paddingClass.sm,
    bgColorClass.transparent,
    textColorClass.black,
    borderWidthClass.base,
    borderColorClass.black,
    hoverClass.opacity,
    shadowClass.none,
  ),
  outlineMini1: flattenClassList(
    fontSizeClass.xs,
    paddingXClass.sm,
    paddingYClass.xs,
    bgColorClass.transparent,
    textColorClass.black,
    borderWidthClass.base,
    borderColorClass.black,
    hoverClass.opacity,
    shadowClass.none,
  ),
  outlineMini2: flattenClassList(
    fontSizeClass.xs,
    paddingXClass.sm,
    paddingYClass.xs,
    bgColorClass.transparent,
    textColorClass.black,
    borderWidthClass.base,
    borderColorClass.black,
    hoverClass.opacity,
    shadowClass.none,
  ),
  ghost: flattenClassList(
    fontSizeClass.caption,
    paddingClass.none,
    bgColorClass.transparent,
    textColorClass.black,
    hoverClass.opacity,
    shadowClass.none,
  ),

  // Responsive Variants
  solidresp: flattenClassList(
    'text-sm sm:text-base md:text-lg',
    'px-4 py-2 sm:px-5 sm:py-3 md:px-6 md:py-4',
    bgColorClass.black,
    textColorClass.white,
    hoverClass.opacity,
    shadowClass.md,
  ),
  softresp: flattenClassList(
    'text-xs sm:text-sm md:text-base',
    'py-2 sm:px-4 sm:py-2',
    bgColorClass.white,
    textColorClass.black,
    borderWidthClass.base,
    borderColorClass.black,
    hoverClass.opacity,
    shadowClass.sm,
  ),
  outlineresp: flattenClassList(
    'text-xs sm:text-sm md:text-base',
    'px-3 py-2 sm:px-5 md:px-6',
    bgColorClass.transparent,
    textColorClass.black,
    borderWidthClass.base,
    borderColorClass.black,
    hoverClass.opacity,
    shadowClass.none,
  ),
  ghostresp: flattenClassList(
    'text-xs sm:text-sm',
    'px-1.5 sm:px-2',
    bgColorClass.transparent,
    textColorClass.black,
    hoverClass.opacity,
    shadowClass.none,
  ),
};
